- name: Déploiement des sites
  hosts: localhost
  become: true
  vars:
   site_content: "<html><body><h1>Ceci est un site </h1></body></html>"
  tasks:
   - name: générer les noms de domaine avec un script
     script: script/script.js
     register: script_out

   - name: Créer les répertoires du sites
     file:
       path: "var/www/{{ item }}"
       state: directory
     loop: {{ script_out.stdout_lines }}

   - name: Copier les contenus
     copy:
       content: {{ site_content }}
       dest: "var/www/{{ item }}/index.html"
     loop: {{ script_out.stdout_lines }}
        - name: Générer les fichiers de configurations d'Apache2
     template:
       src: "host.conf"
       dest: "/etc/apache2/sites-available/{{ item }}.conf"
     loop: {{ script_out.stdout_lines }}
     notify: Reload Apache2

   - name: Activer les sites Apache2
      ommand: a2ensite {{ item }}.conf
      loop: "{{ generated_domains.stdout_lines }}"
      notify: Reload Apache2

  handlers:
    - name: Reload Apache2
      service:
        name: apache2
        state: reloaded